version: "3.4"

services:
  simple-links:
    image: fascinated/simple-links:latest
    # Uncomment the following line to build the image yourself
    # build: https://git.fascinated.cc/Fascinated/simple-links.git
    # or build it locally (you need to clone the repo first):
    # build:
    #   context: .
    container_name: SimpleLinks
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./config.yml:/usr/src/app/config.yml:ro # The application config (Must be created before starting the service)
      - ./public:/usr/src/app/public:rw # Used for public facing images (eg: avatar and background)
