version: "3.4"

services:
  next-app:
    build: https://git.fascinated.cc/Fascinated/simple-links.git
    # Use this below if you want to build the image locally (you need to clone the repo first)
    # build: .
    # image: fascinated/simple-links
    restart: always
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    volumes:
      - ./config.json:/usr/src/app/config.json
