version: "3.4"

services:
  simple-links:
    image: fascinated/simple-links:latest
    # Uncomment the following line to build the image yourself
    # build: https://git.fascinated.cc/Fascinated/simple-links.git
    # or build it locally (you need to clone the repo first):
    # build:
    #   context: .
    restart: always
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    volumes:
      - ./config.json:/usr/src/app/config.json:ro
